# Generated by Django 3.1.4 on 2020-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_year', models.IntegerField()),
                ('max_year', models.IntegerField()),
                ('min_mileage', models.IntegerField()),
                ('max_mileage', models.IntegerField()),
                ('fuel', models.CharField(max_length=64)),
                ('drive_type', models.CharField(max_length=128)),
            ],
        ),
    ]
