# Generated by Django 3.1.4 on 2020-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20201226_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='drive_type',
            field=models.CharField(choices=[('1', 'Повний'), ('2', 'Передній'), ('3', 'Задній'), ('4', 'Кардан'), ('5', 'Ремінь'), ('6', 'Ланцюг')], max_length=128),
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='fuel',
            field=models.CharField(choices=[('1', 'Бензин'), ('2', 'Дизель'), ('3', 'Газ'), ('4', 'Газ / Бензин'), ('5', 'Гібрид'), ('6', 'Електро'), ('7', 'Інше'), ('8', 'Газ метан'), ('9', 'Газ пропан-бутан')], max_length=64),
        ),
    ]
