# Generated by Django 3.1.4 on 2021-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20201230_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='brand',
            field=models.CharField(max_length=128),
        ),
    ]
