# Generated by Django 3.1.4 on 2021-01-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20210104_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.autoriabrandmodel'),
        ),
    ]
